# $Id: makefile 17995 2004-10-28 10:10:01Z gvandiep $

XLIBLIST := CFITSIO LAPACK F77

# Use the generic AIPS++ test makefile.
#--------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
