# $Id$

COMPONENTS := ms msplot

XLIBLIST:= CCMTOOLS PYTHON ATM

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(CASAPATH))/code/xmlcasa/install/makefile.cimp

