# $Id: makefile 17722 2004-08-24 21:32:54Z cvsmgr $

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
