# $Id$

# Use the generic AIPS++ test makefile.
#--------------------------------------
PGPLOTLIBD := /usr/local/lib
PGPLOTLIB  := -lpgplot
XLIBLIST := PGPLOT X11 F77
include $(word 1, $(CASAPATH))/code/install/makefile.tst
