# $Id: makefile 17924 2004-10-11 02:11:32Z nkilleen $

# Use the generic AIPS++ test makefile.
#--------------------------------------
XLIBLIST := WCSLIB LAPACK F77 CFITSIO
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
