# $Id: makefile 17758 2004-08-24 22:54:27Z cvsmgr $

# Use the generic AIPS++ test makefile.
#--------------------------------------
XLIBLIST := LAPACK F77
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
