# $Id: makefile 17689 2004-08-24 20:45:47Z cvsmgr $

# Use the generic AIPS++ test makefile.
#--------------------------------------
XLIBLIST := LAPACK F77
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
