# $Id$

# Use the generic AIPS++ test makefile.
#--------------------------------------
XLIBLIST :=MIRLIB CFITSIO LAPACK F77 WCSLIB MPI ATM PGPLOT
include $(word 1, $(CASAPATH))/code/install/makefile.tst
