# $Id$

# Use the generic AIPS++ test makefile.
#--------------------------------------
XLIBLIST :=MIRLIB CFITSIO LAPACK F77 WCSLIB MPI ATM PGPLOT X11 Motif
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
