#!/bin/sh

aipspath=($CASAPATH)
CASAROOT=${aipspath[0]}/${aipspath[1]}

case $(uname) in
  Darwin)
     echo "Adjust this as it will cause problems for Boyd with the distro"
     $CASAROOT/apps/qcasabrowser.app/Contents/MacOS/qcasabrowser $@
  ;;
  Linux)
	$CASAROOT/bin/qcasabrowser $@
  ;;
esac
