# $Id$

XLIBLIST:= CCMTOOLS CFITSIO PYTHON PGPLOT WCSLIB

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(CASAPATH))/code/xmlcasa/install/makefile.cimp

