# $Id$
XLIBLIST:=WCSLIB PGPLOT TCL Motif X11 XPM
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.imp
