# $Id: makefile 17724 2004-08-24 21:35:33Z cvsmgr $

# Use the generic AIPS++ class implementation makefile
#-----------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
