sys.path.append('/homes/hafok/HEAD/PIPELINE/Heuristics/src/heuristics') 
import SFIPipelineStagesInterface
sfi=SFIPipelineStagesInterface.SFIPipelineStagesInterface()
sfi.setRawDirectory('/homes/hafok/PipelineWork/test')
sfi.setRawFile('vla_g28-D-spwid2.raw')
sfi.setOutDirectory('/homes/hafok/PipelineWork/output')
sfi.setObservatoryVLA()
sfi.setMosaicMode(False)

sfi.setupSFIReducer()

sfi.flagByRule(rule='autocorrelation')
sfi.plotInitalBandpassCalCoeffs()
sfi.plotInitialFluxCalCoeff()
sfi.plotMSCleanedImages()
sfi.flagCalibratorNoisyAmplitudes()
sfi.flagCalibratorNoisyPhases
sfi.flagCalibratorAntennaSingleAmplitudes()
sfi.plotCalibratorPhaseBehaviour()
sfi.flagCalibratorBaselineAmplitudes()
sfi.detectBandpassEdge()
sfi.findBandpassCalibration()
sfi.plotBandpassCalibration()
sfi.flagBandpassCalibrationVLA()
sfi.flagLowSNRCalibration()
sfi.flagPhaseJumpCalibration()
sfi.flagTargetDataAntennaSingleAmplitudes()
sfi.flagLargeGainClosureErrors()
sfi.flagLargeTargetClosureMagnitude()
sfi.plotBandpassCalibrationCoeffs()
sfi.plotFluxCalibrationCoeffs()
sfi.plotVisibilities()
sfi.plotVisibilityAmplitudes()
sfi.plotCalibratorCleanedCube()
sfi.plotCalibratorsSpectra()
sfi.plotTargetCleanedCube()
sfi.plotTargetCleanMap()
sfi.plotTargetsSpectra()
