#!/bin/bash

aipspath=($CASAPATH)
CASAROOT=${aipspath[0]}/${aipspath[1]}

if test -x $CASAROOT/apps/qcasabrowser.app/Contents/MacOS/qcasabrowser; then
    echo "Adjust this as it will cause problems with the distro"
    exec $CASAROOT/apps/qcasabrowser.app/Contents/MacOS/qcasabrowser $@
fi

if test -x $CASAROOT/bin/qcasabrowser; then
    exec $CASAROOT/bin/qcasabrowser $@
fi

echo "Cannot find a usable qcasabrowser..."
exit 1
