#!/bin/sh
#-----------------------------------------------------------------------------
# Usage: tTable_2.exec
#-----------------------------------------------------------------------------
# This scripts executes the program tTable_2 to test if new table
# software can still read old tables.
# The script supplies the names of all test tables found in the system.
# It is meant to be run from assay, but can also be used standalone.
#
# $Id: tTable_2.run 21130 2011-10-18 07:39:05Z gervandiepen $
#-----------------------------------------------------------------------------

# Fundamentals.
  TABLES="$testsrcdir/tTable_2.data_v*"

  $casa_checktool ./tTable_2 $TABLES
