#ifndef _casatypes_idl_
#define _casatypes_idl_

#include <basicVecs.idl>
         
module casac
{  
   struct Quantity {
     DoubleVec value;
     string units;
   };

   typedef string MDirection;
   typedef string MRadialVelocity;
   typedef string MPosition;
};
#endif
