# $Id: makefile,v 1.1 2009/08/18 20:18:35 pteuben Exp $ 

# Use the generic AIPS++ package makefile.
#-----------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.pkg
