#!/bin/sh

usage() {
   echo "Usage: $iam [--help] [--verbose] [--installdir=<dir>] [--outputfile=<file>] [<XML files>]"
   echo "  --help              : this help screen"
   echo "  --verbose           : print a diagnostic to standard output"
   echo "  --installdir=<dir>  : directory where Casa local tasks were installed (default is \`pwd\`)"
   echo "  --outputfile=<file> : name of the output file (default is \"mytasks.py\")"
   echo "  <XML files>         : list of XML files that describes Casa tasks (by default all XML files of the current directory)"
}

iam=`basename $0`
WORKDIR=`pwd`
xmlfiles=
while [ "$#" -gt 0 ]
  do
   case $1 in
     --help)
       usage
       exit
       ;;
    --verbose)
      VERBOSE="on"
      ;;
    --installdir=*)
      TMP=$1
      INSTALLDIR=`echo $TMP | sed 's/[-a-zA-Z0-9]*=//'`
      echo "Install directory  is " $INSTALLDIR
      ;;
    --outputfile=*)
      TMP=$1
      OUTPUTFILE=`echo $TMP | sed 's/[-a-zA-Z0-9]*=//'`
      echo "output file is " $OUTPUTFILE
      ;;
    *)
      xmlfiles="${xmlfiles} $1"
      ;;
    esac
    shift
  done

if [ -z $VERBOSE ]; then
  VERBOSE="off"
fi
if [ -z $INSTALLDIR ]; then
  INSTALLDIR=`pwd`
fi
if [ -z $OUTPUTFILE ]; then
  OUTPUTFILE="mytasks.py"
fi
if [ -z $xmlfiles ]; then
  xmlfiles=`ls *.xml`
fi

if [ ! -d "$INSTALLDIR" ]; then
  echo "Creating $INSTALLDIR"
  amkdir $INSTALLDIR
fi

echo "Installing "$OUTPUTFILE" into "$INSTALLDIR
OUTFILE=$INSTALLDIR/$OUTPUTFILE

CASAROOT=`echo $CASAPATH | awk '{print $1}'`
CASAARCH=`echo $CASAPATH | awk '{printf "%s/%s", $1, $2}'`
INFOFILE=/tmp/.casapy.taskinfo
SAXONJAR=${CASAARCH}/lib/saxon8.jar
if [ ! -e ${SAXONJAR} ] ; then
	SAXONJAR=${CASAROOT}/java/saxon8.jar
fi
SAXON="java -jar ${SAXONJAR}"
cp /dev/null ${INFOFILE}

for file in $xmlfiles
do
  xmlfile=${file%.xml}
  if [[ "$VERBOSE" == "on" ]]; then echo "Generating $xmlfile task ..."; fi
  xmlgenpy $xmlfile
  ${SAXON} ${xmlfile}.xml ${CASAROOT}/share/xml/casa2tsum2.xsl >> ${INFOFILE}
  sed -e 's+pathname=.*$+pathname="file://${INSTALLDIR}/"+' ${xmlfile}.py > tmp${xmlfile}.py
  mv tmp${xmlfile}.py ${xmlfile}.py
  if [[ "${INSTALLDIR}" != "${WORKDIR}" ]] ; then
     mv ${xmlfile}.py ${INSTALLDIR}
     mv ${xmlfile}_cli.py ${INSTALLDIR}
     cp ${xmlfile}.xml ${INSTALLDIR}
     cp task_${xmlfile}.py ${INSTALLDIR}
  fi
  if [[ "$VERBOSE" == "on" ]]; then echo "${xmlfile} task files installed into ${INSTALLDIR}"; fi
done

if [[ "$VERBOSE" == "on" ]]; then echo "Generating $OUTFILE file ..."; fi

sed -e s/^tasksum/mytasks/g ${INFOFILE} > /tmp/.casapy.taskinfo2
mv /tmp/.casapy.taskinfo2 ${INFOFILE}

cat /dev/null > ${OUTFILE}
echo "#User defined tasks setup" >> ${OUTFILE}
echo "#Generated from buildmytask" >> ${OUTFILE}
echo >> ${OUTFILE}
echo "sys.path.append('"$INSTALLDIR"')" >> ${OUTFILE}
echo "from odict import odict" >> ${OUTFILE}
echo "if not globals().has_key('mytasks') :" >> ${OUTFILE}
echo "   mytasks = odict()" >> ${OUTFILE}
echo >> ${OUTFILE}
grep "^mytasks" ${INFOFILE} >> ${OUTFILE}
echo >> ${OUTFILE}
echo "if not globals().has_key('task_location') :" >>${OUTFILE}
echo "   task_location = odict()" >> ${OUTFILE}
echo >> ${OUTFILE}
echo "for key in mytasks.keys() :" >> ${OUTFILE}
echo "   task_location[key] = '${INSTALLDIR}'" >> ${OUTFILE}
echo "   tasksum[key] = mytasks[key]" >> ${OUTFILE}
echo >> ${OUTFILE}
grep "^from" ${INFOFILE} >> ${OUTFILE}
rm -f ${INFOFILE}


