# $Id: makefile 17902 2004-09-29 14:16:03Z gvandiep $

XLIBLIST := WCSLIB MIRLIB CFITSIO

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
