# $Id$

XLIBLIST := LOG4CPLUS CCMTOOLS PYTHON

# Use the generic AIPS++ class implementation makefile
#-----------------------------------------------------
include $(word 1, $(CASAPATH))/code/xmlcasa/install/makefile.cimp
