/*
 * This file was automatically generated by 
 * <http://ccmtools.sourceforge.net/>
 * DO NOT EDIT !
 */

// ===========================================================================
// struct definition for ComplexAry
// ===========================================================================

#ifndef __STRUCT__CCM_Local_casac_ComplexAry__H__
#define __STRUCT__CCM_Local_casac_ComplexAry__H__

#include<string>
#include <vector>
#include <xmlcasa/complex.h> 

namespace casac {

struct ComplexAry
{
  ComplexAry( ) { }
  ComplexAry(std::vector<casac::complex> arg0, std::vector<int> arg1) : value(arg0), shape(arg1) { }
  std::vector<casac::complex> value;
  std::vector<int> shape;

};

} // / namespace casac

#endif // __STRUCT__CCM_Local_casac_ComplexAry__H__

