/*
 * This file was automatically generated by 
 * <http://ccmtools.sourceforge.net/>
 * DO NOT EDIT !
 */

// ===========================================================================
// struct definition for DoubleAry
// ===========================================================================

#ifndef __STRUCT__CCM_Local_casac_DoubleAry__H__
#define __STRUCT__CCM_Local_casac_DoubleAry__H__

#include<string>
#include <vector>

namespace casac {

struct DoubleAry
{
  DoubleAry( ) { }
  DoubleAry(std::vector<double> arg0, std::vector<int> arg1) : value(arg0), shape(arg1) { }
  std::vector<double> value;
  std::vector<int> shape;

};

} // / namespace casac

#endif // __STRUCT__CCM_Local_casac_DoubleAry__H__

