/*
 * This file was automatically generated by 
 * <http://ccmtools.sourceforge.net/>
 * DO NOT EDIT !
 */

// ===========================================================================
// struct definition for Quantity
// ===========================================================================

#ifndef __STRUCT__CCM_Local_casac_Quantity__H__
#define __STRUCT__CCM_Local_casac_Quantity__H__

#include<string>
#include <vector>

namespace casac {

struct Quantity
{
  Quantity( ) { }
  Quantity(std::vector<double> arg0, std::string arg1) : value(arg0), units(arg1) { }
  std::vector<double> value;
  std::string units;

};

} // / namespace casac

#endif // __STRUCT__CCM_Local_casac_Quantity__H__

