# Fundamentals
#-------------
AIPSROOT := $(word 1, $(CASAPATH))


# Use the generic AIPS++ documentation makefile
#----------------------------------------------
include $(AIPSROOT)/code/install/makefile.doc

HTLATEXOPTS := "htcasa,section+,next,p-width,1"
