#!/bin/bash
if [[ -L "$0"  ]]; then
   real_me=$(stat -f %Y "$0")
   myDir=$(dirname "$real_me")
   echo -n '==>  '
else
   myDir=$(dirname "$0")
fi
prefix=$(dirname "${myDir}")
CASAROOT=${prefix}/..
appSig=$(/usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" "${CASAROOT}/Info.plist" )
thisVersion=$(awk '{print $1}' "${CASAROOT}/Resources/VERSION")
setupMode=$(defaults read "${appSig}" "casa.setup.mode")
updateCasa="false"
linkthese=$(/usr/libexec/PlistBuddy -c "Print :MakeLinks" "${CASAROOT}/Info.plist" | awk '/^ /{print $0}')
echo "Executeables to link" ${linkthese}

savedVersion=$(defaults read "${appSig}" "casa.version")
if [ -n ${savedVersion} ]; then
	if [ "${savedVersion}" != "${thisVersion}" ]; then
            updateCasa="true"
	fi
else
   updateCasa="true"
fi

updateCasa="true"

if [ "${updateCasa}" = "true" ]; then
   cmdlineLinks=$(defaults read "${appSig}" "casa.setup.linkdir")
   if [ -n "${cmdlineLinks}" ]; then
	   message="Update your CASA symbolic links?"
   else
	   # Haven't setup command line symbolic links yet
	   message="Please enter in a directory in your PATH that you wish to install CASA symbolic links"
   fi
   linkdir=`/usr/bin/osascript 2>/dev/null <<EOT
tell application "System Events"
  activate
  set myReply to text returned of (display dialog "${message}" with title "CASA shell environment setup" default answer "/usr/bin" buttons {"Create Symlinks", "Cancel"} default button 1)
end tell
EOT`

cat /dev/null > /tmp/mkcasalinks
chmod a+x /tmp/mkcasalinks
   linksGoHere=${linkdir}
   if [ -n ${linksGoHere} ]; then
           for file in ${linkthese}
           do
              echo "ln -sf ${CASAROOT}/MacOS/${file} ${linksGoHere}" >> /tmp/mkcasalinks
           done
	   if [ -d ${linksGoHere} ]; then
	      if [ -w ${linksGoHere} ]; then
		      echo "Create the symbolic links ${linksGoHere}"
		      /tmp/mkcasalinks
	      else
                      admlinkdir=`/usr/bin/osascript << EOT
	      do shell script "/tmp/mkcasalinks" administrator privileges true
		      EOT`
		      blah=${admlinkdir}
		      echo "Returned to sender " ${blah}
	      fi
	      # rm /tmp/mkcasalinks
	   else
	      echo "${linksGoHere} is not a directory!"
	   fi
   fi
   echo $appSig
   echo $thisVersion
   echo $setupMode
   echo $?
fi
