# $Id: makefile 17685 2004-08-24 20:36:15Z cvsmgr $

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
