# $Id$
EXTRA_C++FLAGS=-fPIC
XLIBLIST := CFITSIO WCSLIB KLUDGEASDM XML2 BOOST
#XLIBLIST := CFITSIO WCSLIB KLUDGEASDM

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.imp
