#!/usr/bin/perl
use File::Basename;
use Cwd 'abs_path';

chomp($root=`casa-config --prefix`);
print "Using CASA installation root: $root\n";
$pipe = abs_path(dirname($0));
$ENV{CASASRC}="$pipe/pipeline";
$ENV{PYVERSION}="2.7";
$ENV{CASAARCH}="$pipe/pipeline";
$ENV{PYTHONPATH}="$pipe/pipeline";
print "Using CASA installation root: $root\n";
print "CASAARCH:                     $ENV{CASAARCH}\n";

chomp($OSNAME=`uname -s`);
if ( $OSNAME eq "Linux" ) {
   print "OSNAME: $OSNAME\n";
   exec "casa-config --exec python setup.py install --install-lib=$ENV{CASAARCH} --install-data=$ENV{CASAARCH} --force";
} else {
   print "WARNING: Could not find CASA's Python !\n"
}
