#!/bin/sh
if [[ -L "$0" ]]; then
	real_me=$(staty -f %Y "$0")
	myDir=$(dirname "$real_me")
else
	myDir=$(dirname "$0")
fi
if [ "$1" = "--release" ]; then
	distro="release"
	RELEASEDIR=$2
else
	distro="programmer"
fi
export CASASRC=$myDir/pipeline
#
OSVERS=$(uname -r | awk -F. '{print $1}')
#if [ $OSVERS -lt "12" ]; then
#export PYVERSION=2.6
#else
export PYVERSION=2.7
#fi
#
if [ $distro = "release" ] ; then
export CASAARCH=$RELEASEDIR/python/$PYVERSION
else 
export CASAARCH=$myDir
fi
echo $CASAARCH
OSNAME=`uname -s`
if [[ $OSNAME = "Linux" ]]; then
echo OSNAME $OSNAME
CASAPY=`which casapy`
TOPLEVEL=`dirname $CASAPY`
if [ -x $TOPLEVEL/lib/casa/bin/python ]; then
   PYTHONEXEC=$TOPLEVEL/lib/casa/bin/python
   echo $PYTHONEXEC
elif [ -x $TOPLEVEL/lib64/casapy/bin/python ]; then
   PYTHONEXEC=$TOPLEVEL/lib64/casapy/bin/python
   echo $PYTHONEXEC
elif [ -x /usr/lib/casa/bin/python ]; then
   PYTHONEXEC=/user/lib/casa/bin/python
   echo $PYTHONEXEC
elif [ -x /usr/lib64/casapy/bin/python ]; then
   PYTHONEXEC=/user/lib64/casapy/bin/python
   echo $PYTHONEXEC
else
   PYTHONEXEC=python
   echo $PYTHONEXEC
fi
else
PYTHONEXEC=python
echo $PYTHONEXEC
fi
export PYTHONPATH=$CASAARCH
$PYTHONEXEC setup.py install --install-lib=$CASAARCH --install-data=$CASAARCH --force
