# $Id: makefile 17923 2004-10-11 01:22:16Z nkilleen $

XLIBLIST := WCSLIB MIRLIB LAPACK F77 CFITSIO

# Use the generic AIPS++ test makefile.
#--------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
