# $Id$
SCRIPTS := casapy.py
EXCLUDE := oldscripts
PACKS := regressions usecases demos parallel tests

# Use the generic AIPS++ script installation makefile.
#-----------------------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.scr
