from tasksinfo import *
def startup():
# startup guide
      """ Start up screen for CASA """
      print '___________________________________________________________'
      print 'Available tasks:\n'
      print '   accum         flagmanager   listhistory   sdsave'
      print '   applycal      fluxscale     listobs       sdscale'
      print '   bandpass      ft            listvis       sdsmooth'
      print '   browsetable   gaincal       makemask      sdstat'
      print '   clean         hanningsmooth mosaic        setjy'
      print '   clearcal      imcontsub     plotants      smoothcal'
      print '   clearplot     imhead        plotcal       specfit'
      print '   clearstat     immoments     plotxy        split'
      print '   concat        importfits    sdaverage     tget'
      print '   deconvolve    importuvfits  sdbaseline    uvcontsub'
      print '   exportfits    importvla     sdcal         uvmodelfit'
      print '   exportuvfits  imregrid      sdciadd       viewer'
      print '   feather       imstat        sdfit         vishead'
      print '   filecatalog   imval         sdflag'
      print '   find          invert        sdlist'
      print '   flagdata      listcal       sdplot'
      print ''
      print 'Additional tasks are available for ALMA commissioning use'
      print '         (still alpha code as of Beta 0 release):'
      print ''
      print ' almasimmos      blcal       fringecal   importasdm'
      print ''
      print 'Available tools:\n'
      print '   cb (calibrater)     cp (cal plot)     fg (flagger)'
      print '   ia (image analysis) im (imager)       me (measures)'
      print '   mp (MS plot)        ms (MS)           qa (quanta)'
      print '   sm (simulation)     tb (table)        tp (table plot)'
      print '   vp (voltage patterns)'
      print ''
      print '   pl (pylab functions)'
      print '   sd (ASAP functions - run asap_init() to import into CASA)'
      print ''
      print '   casalogger             - Call up the casalogger (if it goes away)'
      print ''
      print '___________________________________________________________________'
      print ''
      print 'Help :   '
      print '   help taskname          - Full help for task'
      print '   help par.parametername - Full help for parameter name '
      print '   find string            - Find occurances of string in doc'
      print '   tasklist               - Task list organized by catagory'
      print '   taskhelp               - One line summary of available tasks'
      print '   toolhelp               - One line summary of available tools'
      print '   startup                - The start up screen'
      print ''
      print '___________________________________________________________________'

def taskhelp():
      """ List all tasks with one-line description: """
      print 'Available tasks: \n'
      print ' '
      for mytask in tasksum.keys() :
	      if len(mytask) < 7 :
	         print mytask,'		:',tasksum[mytask]
	      else :
	         print mytask,'	:',tasksum[mytask]
      print ' '


def toolhelp():
      """ List all tools with one-line description: """
      print ' '
      print 'Available tools: \n'
      print ' at : Juan Pardo ATM library'
      print ' cb : Calibration utilities'
      print ' cp : Cal solution plotting utilities'
      print ' fg : Flagging/Flag management utilities'
      print ' ia : Image analysis utilities'
      print ' im : Imaging utilities'
      print ' me : Measures utilities'
      print ' ms : MeasurementSet (MS) utilties'
      print ' mp : MS plotting (data (amp/phase) versus other quantities)'
      print ' tb : Table utilities (selection, extraction, etc)'
      print ' tp : Table plotting utilities'
      print ' qa : Quanta utilities'
      print ' sm : Simulation utilities'
      print ' vp : Voltage pattern/primary beam utilties'
      print ' ---'
      print ' pl : pylab functions (e.g., pl.title, etc)'
      print ' ---'


def tasklist():
      """ List tasks, organized by catagory """
      print 'Available tasks: \n'
      print 'Import/Export    Information  Data Editing  Display/Plot'
      print '-------------    -----------  ------------  ------------'
      print 'importvla        listcal      flagautocorr  clearplot'
      print '(importasdm)     listhistory  flagdata      plotants '
      print 'importfits       listobs      flagmanager   plotcal'    
      print 'importuvfits     listvis      plotxy        plotxy'
      print 'exportfits       imhead                     viewer'
      print 'exportuvfits     imstat'
      print '                 vishead'
      print ''
      print 'Calibration      Imaging      Modelling     Utility'
      print '-----------      -------      ---------     -------'
      print 'accum            clean        setjy         help task'
      print 'applycal         deconvolve   uvcontsub     help par.parameter'
      print 'bandpass         feather      uvmodelfit    taskhelp'
      print '(blcal)          ft                         tasklist'
      print 'gaincal          invert                     browsetable'
      print 'fluxscale        makemask                   clearplot'
      print '(fringecal)      mosaic                     clearstat'
      print 'clearcal                                    concat'
      print 'listcal                                     filecatalog'
      print 'smoothcal                                   startup'
      print 'polcal                                      split'
      print 'hanningsmooth                                  '
      print '                                                 '
      print ''
      print 'Image Analysis   Simulation   Single Dish'
      print '--------------   ----------   -----------'
      print 'imcontsub        (almasimmos) sdaverage'
      print 'imhead                        sdbaseline'
      print 'immath                        sdcal'
      print 'immoments                     sdcoadd'
      print 'imregrid                      sdfit'
      print 'imstat                        sdflag'
      print 'imval                         sdlist'
      print 'specfit                       sdplot'
      print '                              sdsave'
      print '                              sdscale'
      print '                              sdsmooth'
      print '                              sdstat'
      if globals().has_key('mytasks') :
         print ''
         print 'User defined tasks'
         print '------------------'
         for key in mytasks.keys() :
             print key


