# $Id: makefile 18698 2005-05-23 07:31:29Z gvandiep $

XLIBLIST := CFITSIO LAPACK F77

# Use the generic AIPS++ test makefile.
#--------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
