XLIBLIST:= XML2 CFITSIO BOOST PYTHON OLDKLUDGEASDM
# Use the generic AIPS++ app makefile.
#------------------------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.app
