# $Id$
XLIBLIST:=WCSLIB CCMTOOLS PYTHON
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.imp
