# $Id$

# HELPACKS ought to be a sed script that generates the package list from the
# Refman.latex source.
DOCSUSER  := $(word 1, $(CASAPATH))/docs/scienceref
#HELPAREA  := $(word 1, $(CASAPATH))/docs/xmlcasa/tasks/helpfiles

#EXTRA_TEXINPUTS := $(HELPAREA)

# Use the generic AIPS++ documentation makefile
#----------------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.doc
