# $Id$
#XLIBLIST := ATM No need for ATM now as it is ATM!
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.imp
