# $Id: makefile 17904 2004-09-30 05:44:56Z gvandiep $

XLIBLIST := CFITSIO

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
