# $Id$
EXTRA_C++FLAGS=-fPIC
#XLIBLIST := CFITSIO WCSLIB KLUDGEASDM ANTLR
XLIBLIST := CFITSIO WCSLIB OLDKLUDGEASDM

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.imp
