# $Id: makefile 19933 2007-02-27 05:04:51Z Malte.Marquarding $

# Use the generic AIPS++ test makefile.
#--------------------------------------
XLIBLIST := WCSLIB LAPACK F77

include $(word 1, $(AIPSPATH))/code/install/makefile.tst
