#!/bin/sh
#-----------------------------------------------------------------------------
# Usage: tTable_2.exec
#-----------------------------------------------------------------------------
# This scripts executes the program tTable_2 to test if new table
# software can still read old tables.
# The script supplies the names of all test tables found in the system.
# It is meant to be run from assay, but can also be used standalone.
#
# $Id: tTable_2.run 20551 2009-03-25 00:11:33Z Malte.Marquarding $
#-----------------------------------------------------------------------------

# Fundamentals.
  TABLES="tTable_2.data_v*"

  ./tTable_2 $TABLES
