# $Id$

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
XLIBLIST := WCSLIB MPI
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
