# $Id$
SCRIPTS := installer.pl process_manager.pl scheduler.pl
PYPACK := regressions/admin

# Use the generic AIPS++ script installation makefile.
#-----------------------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.scr
