# $Id$

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
XLIBLIST := CORE WCSLIB MPI
include $(word 1, $(CASAPATH))/code/install/makefile.imp
