# $Id: makefile 19989 2007-02-28 10:56:54Z Malte.Marquarding $

# Use the generic AIPS++ package makefile.
#-----------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.pkg
