# $Id: makefile 17751 2004-08-24 22:23:35Z cvsmgr $

# Use the generic AIPS++ test makefile.
#--------------------------------------
XLIBLIST := F77
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
