# $Id$

XLIBLIST := CORE QT4

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(CASAPATH))/code/xmlcasa/install/makefile.mod
foo:	
	echo $(CORELIBD)
	echo $(CORELIB)
	echo $(COREINCD)
