# $Id: makefile,v 1.2 2009/09/03 18:56:10 pteuben Exp $

XLIBLIST := MIRLIB

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.imp

