# $Id: makefile 20551 2009-03-25 00:11:33Z Malte.Marquarding $
EXTRA_C++FLAGS=-fPIC
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
