# $Id: makefile 20551 2009-03-25 00:11:33Z Malte.Marquarding $

# Use the generic AIPS++ package makefile.
#-----------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.pkg
