# $Id: makefile 17779 2004-08-24 23:40:08Z cvsmgr $

# Use the generic AIPS++ test makefile.
#--------------------------------------
XLIBLIST := LAPACK F77
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
