/*
 * This file was automatically generated by 
 * <http://ccmtools.sourceforge.net/>
 * DO NOT EDIT !
 */

// ===========================================================================
// struct definition for complex
// ===========================================================================

#ifndef __STRUCT__CCM_Local_casac_complex__H__
#define __STRUCT__CCM_Local_casac_complex__H__

#include<string>

namespace casac {

struct complex
{
  complex( ) { }
  complex(double arg0, double arg1) : re(arg0), im(arg1) { }
  double re;
  double im;

};

} // / namespace casac

#endif // __STRUCT__CCM_Local_casac_complex__H__

