import os,glob,shutil

# import root environment
Import( "env")
myenv = env.Copy()

if myenv["makedoc"].lower() == 'pdf':
    dvif = myenv.File("userguide.tex")
    pdf = env.PDF(dvif)
elif myenv["makedoc"].lower() == 'html':
    if os.path.exists("/usr/bin/latex2html"):
        myenv.Command("userguide","userguide.tex",
                      "/usr/bin/latex2html -local_icons $TARGET" )
