# $Id: makefile 17872 2004-09-24 21:31:30Z gli $
XLIBLIST  := CFITSIO
# Use the generic AIPS++ test makefile.
#--------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
