# $Id$

XLIBLIST := XERCES READLINE CCMTOOLS

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(CASAPATH))/code/xmlcasa/install/makefile.cimp
