# $Id: makefile 17729 2004-08-24 21:41:23Z cvsmgr $

# Use the generic AIPS++ class implementation makefile.
# ------------------------------------------------------
XLIBLIST := WCSLIB 
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
