# $Id$
XLIBLIST:=WCSLIB PGPLOT Motif XPM X11
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.imp
