XLIBLIST:= KLUDGEASDM_V3 XML2 CFITSIO BOOST PYTHON
# Use the generic AIPS++ app makefile.
#------------------------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.app
