# $Id$
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
XLIBLIST:=PGPLOT WCSLIB
include $(word 1, $(CASAPATH))/code/install/makefile.imp
