# $Id$
XLIBLIST := ATM
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------

#
# This is a bit of a kludge, we expect a special makedefs file that specifies the 
# include directory for ATMINCD, if that's set we build with atmosphere otherwise
# we don't
#
include $(word 1, $(CASAPATH))/code/xmlcasa/install/makefile.cimp
