# $Id: makefile 17707 2004-08-24 21:11:49Z cvsmgr $

# Use the generic AIPS++ class implementation makefile
#-----------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
