# $Id$

TIROOT := $(word 1, $(CASAPATH))/code/doc

# Use the generic AIPS++ documentation makefile
#----------------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.doc

HTLATEXOPTS := "htcasa,info,section+,next,p-width,3"
