# $Id: makefile 17773 2004-08-24 23:29:58Z cvsmgr $

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
