# $Id$

XLIBLIST := TCL TK CFITSIO Motif PGPLOT WCSLIB XPM X11 LAPACK F77 GLISH MIRLIB

# Use the generic AIPS++ test makefile.
#--------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.tst
