/*
 * This file was automatically generated by 
 * <http://ccmtools.sourceforge.net/>
 * DO NOT EDIT !
 */

// ===========================================================================
// struct definition for BoolAry
// ===========================================================================

#ifndef __STRUCT__CCM_Local_casac_BoolAry__H__
#define __STRUCT__CCM_Local_casac_BoolAry__H__

#include<string>
#include <vector>

namespace casac {

struct BoolAry
{
  BoolAry( ) { }
  BoolAry(std::vector<bool> arg0, std::vector<int> arg1) : value(arg0), shape(arg1) { }
  std::vector<bool> value;
  std::vector<int> shape;

};

} // / namespace casac

#endif // __STRUCT__CCM_Local_casac_BoolAry__H__

