/*
 * This file was automatically generated by 
 * <http://ccmtools.sourceforge.net/>
 * DO NOT EDIT !
 */

// ===========================================================================
// struct definition for StringAry
// ===========================================================================

#ifndef __STRUCT__CCM_Local_casac_StringAry__H__
#define __STRUCT__CCM_Local_casac_StringAry__H__

#include<string>
#include <vector>

namespace casac {

struct StringAry
{
  StringAry( ) { }
  StringAry(std::vector<std::string> arg0, std::vector<int> arg1) : value(arg0), shape(arg1) { }
  std::vector<std::string> value;
  std::vector<int> shape;

};

} // / namespace casac

#endif // __STRUCT__CCM_Local_casac_StringAry__H__

