#ifndef casa_basicvecs_idl__
#define casa_basicvecs_idl__

#include <complex.idl>

module casac {

    typedef sequence<long>		IntVec;
    typedef sequence<string>		StringVec;
    typedef sequence<double>		DoubleVec;
    typedef sequence<boolean>		BoolVec;
    typedef sequence<complex>		ComplexVec;

    typedef sequence<long>		shape_type;

    struct IntAry {
      IntVec value;
      shape_type shape;
    };
    struct StringAry {
      StringVec value;
      shape_type shape;
    };
    struct DoubleAry {
      DoubleVec value;
      shape_type shape;
    };
    struct BoolAry {
      BoolVec value;
      shape_type shape;
    };
   struct ComplexAry {
      ComplexVec value;
      shape_type shape;
   };

};

#endif
