#!/usr/bin/env python


from imstat_pg import imstat_pg as imstat
from flagdata_pg import flagdata_pg as flagdata
from flagcmd_pg import flagcmd_pg as flagcmd
from importevla_pg import importevla_pg as importevla
from split_pg import split_pg as split
from oldsplit_pg import oldsplit_pg as oldsplit
from importvla_pg import importvla_pg as importvla
from hanningsmooth_pg import hanningsmooth_pg as hanningsmooth
from oldhanningsmooth_pg import oldhanningsmooth_pg as oldhanningsmooth
from widefield_pg import widefield_pg as widefield
from immoments_pg import immoments_pg as immoments
from uvcontsub_pg import uvcontsub_pg as uvcontsub
from listhistory_pg import listhistory_pg as listhistory
from mosaic_pg import mosaic_pg as mosaic
from importfits_pg import importfits_pg as importfits
from imfit_pg import imfit_pg as imfit
from deconvolve_pg import deconvolve_pg as deconvolve
from simalma_pg import simalma_pg as simalma
from simanalyze_pg import simanalyze_pg as simanalyze
from simobserve_pg import simobserve_pg as simobserve
from importasdm_pg import importasdm_pg as importasdm
from uvmodelfit_pg import uvmodelfit_pg as uvmodelfit
from clearcal_pg import clearcal_pg as clearcal
from delmod_pg import delmod_pg as delmod
from bandpass_pg import bandpass_pg as bandpass
from asdmsummary import  asdmsummary
from listvis_pg import listvis_pg as listvis
from accum_pg import accum_pg as accum
from concat_pg import concat_pg as concat
from listobs_pg import listobs_pg as listobs
from feather_pg import feather_pg as feather
from imregrid_pg import imregrid_pg as imregrid
from listcal_pg import listcal_pg as listcal
from listpartition_pg import listpartition_pg as listpartition
from ft_pg import ft_pg as ft
from importuvfits_pg import importuvfits_pg as importuvfits
from setjy_pg import setjy_pg  as setjy
from clean_pg import clean_pg as clean
from immath_pg import immath_pg as immath
from imhead_pg import imhead_pg as imhead
from find_pg import find_pg as find
from gaincal_pg import gaincal_pg as gaincal
from fluxscale_pg import fluxscale_pg as fluxscale
from applycal_pg import applycal_pg as applycal
from exportuvfits_pg import exportuvfits_pg as exportuvfits
from flagmanager_pg import flagmanager_pg as flagmanager
from specfit_pg import specfit_pg  as specfit
from exportfits_pg import exportfits_pg as exportfits
from blcal_pg import blcal_pg as blcal
from uvsub_pg import uvsub_pg as uvsub
from imcontsub_pg import imcontsub_pg as imcontsub
from imstat_pg import imstat_pg as imstat
from clearstat_pg import clearstat_pg as clearstat
from browsetable_pg import browsetable_pg as browsetable
from smoothcal_pg import smoothcal_pg as smoothcal
from imval_pg import imval_pg as imval
from vishead_pg import vishead_pg as vishead
from visstat_pg import visstat_pg as visstat
from calstat_pg import calstat_pg as calstat
from partition_pg import partition_pg as partition
from mstransform_pg import mstransform_pg as mstransform
#from split2_pg import split2_pg as split2
#from hanningsmooth2_pg import hanningsmooth2_pg as hanningsmooth2
from cvel2_pg import cvel2_pg as cvel2
from plotms_pg import plotms_pg as plotms
from tclean_pg import tclean_pg as tclean
from tclean2_pg import tclean2_pg as tclean2
from impbcor_pg import impbcor_pg as impbcor

# single dish tasks
from sdaverage_pg import sdaverage_pg as sdaverage
from sdbaseline_pg import sdbaseline_pg as sdbaseline
from sdbaseline2_pg import sdbaseline2_pg as sdbaseline2
from sdcal_pg import sdcal_pg as sdcal
from sdcal2_pg import sdcal2_pg as sdcal2
from sdcoadd_pg import sdcoadd_pg as sdcoadd
from sdfit_pg import sdfit_pg as sdfit
from sdflag_pg import sdflag_pg as sdflag
from sdflagmanager_pg import sdflagmanager_pg as sdflagmanager
from sdgrid_pg import sdgrid_pg as sdgrid
from sdimaging_pg import sdimaging_pg as sdimaging
from sdimprocess_pg import sdimprocess_pg as sdimprocess
from sdlist_pg import sdlist_pg as sdlist
from sdmath_pg import sdmath_pg as sdmath
from sdplot_pg import sdplot_pg as sdplot
from sdreduce_pg import sdreduce_pg as sdreduce
from sdsave_pg import sdsave_pg as sdsave
from sdscale_pg import sdscale_pg as sdscale
from sdstat_pg import sdstat_pg as sdstat
from tsdbaseline_pg import  tsdbaseline_pg as tsdbaseline
from tsdcal_pg import  tsdcal_pg as tsdcal
from tsdfit_pg import  tsdfit_pg as tsdfit
from tsdsmooth_pg import  tsdsmooth_pg as tsdsmooth

# EOF
