# $Id: makefile 17734 2004-08-24 21:47:23Z cvsmgr $

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
XLIBLIST := WCSLIB
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
