# $Id: makefile,v 1.1 2009/08/18 20:44:26 pteuben Exp $

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.imp
