# $Id: makefile 19610 2006-09-14 03:32:35Z gvandiep $

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
