#!/bin/sh
#-----------------------------------------------------------------------------
# svnchangesby - shell script to extract information for a particular developer
#-----------------------------------------------------------------------------
#
#   Copyright (C) 2006
#   Associated Universities, Inc. Washington DC, USA.
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   Correspondence concerning AIPS++ should be addressed as follows:
#          Internet email: aips2-request@nrao.edu.
#          Postal address: AIPS++ Project Office
#                          National Radio Astronomy Observatory
#                          520 Edgemont Road
#                          Charlottesville, VA 22903-2475 USA
#
#-----------------------------------------------------------------------------
# Fundamentals.
if [ ! "$CASAPATH" ]
then
   echo "svnchangesby: CASAPATH is not defined, abort!"
   exit 1
fi


trap 'echo "svnchangesby aborting..." ; \
      exit' 1 2 3 15

# Check number of arguments.
if [ $# = 0 ]
then
   echo "Usage: svnchangeby ansvn.userid [-r svn revison syntax]"
   exit 1
fi

REL=""

WHO=$1;
shift
while [ "$#" -gt 0 ]
do
    case $1 in
        -r)
            shift
	    REL="-r $1"
	    shift
	    ;;
	*)
	    shift
	    ;;
    esac
done

CASAROOT=`echo $CASAPATH | awk '{print $1}'`
#
# So we find the rev numbers for the individual and loop over them to get detailed 
# information
#
therevs=`svn log --stop-on-copy $REL $CASAROOT/code | grep $WHO | awk '{print $1}' | sed -e s/r//`
for arev in $therevs
do
   svn log -v -r $arev $CASAROOT/code
done
