# $Id$

# Use the generic AIPS++ application makefile.
#---------------------------------------------
XLIBLIST := READLINE CFITSIO PYTHON CCMTOOLS QT4 PGPLOT X11 XERCES ATM C++DBUS
include $(word 1, $(CASAPATH))/code/install/makefile.app
