# $Id$
XLIBLIST := PYTHON CCMTOOLS
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.imp

