# $Id$

XLIBLIST := WCSLIB MIRLIB LAPACK F77 CFITSIO PYTHON BOOST

# Use the generic AIPS++ test makefile.
#--------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.tst
