# $Id: makefile 20551 2009-03-25 00:11:33Z Malte.Marquarding $
 
# Use the generic AIPS++ checkout makefile.
#------------------------------------------
include $(word 1,$(AIPSPATH))/code/install/makefile.chk
