# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
XLIBLIST := CFITSIO LAPACK F77 WCSLIB MIRLIB
include $(word 1, $(CASAPATH))/code/install/makefile.imp
