# $Id: makefile 17723 2004-08-24 21:33:29Z cvsmgr $

# Use the generic AIPS++ test makefile.
#--------------------------------------
XLIBLIST := LAPACK F77
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
