# $Id: makefile 17783 2004-08-25 00:30:19Z cvsmgr $

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
