# $Id$
XLIBLIST := CORE WCSLIB QT4 
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.imp
