# $Id$
SCRIPTS := casapy.py
PACKS := admin tests
PYPACK := regressions

# Use the generic AIPS++ script installation makefile.
#-----------------------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.scr
