# $Id$

# Use the generic AIPS++ package makefile.
#-----------------------------------------
include $(word 1, $(CASAPATH))/code/xmlcasa/install/makefile.cimp

$(GENERATEDCODE)/basicVecs.idl : $(GENERATEDCODE)/complex.idl $(CODEDIR)/basicVecs.idl


