# $Id$
#EXTRA_C++FLAGS=-fPIC
#XLIBLIST := CFITSIO WCSLIB KLUDGEASDM
XLIBLIST := KLUDGEASDM BOOST

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.imp
