# $Id$
XLIBLIST:=GLISH Motif PGPLOT WCSLIB X11 XPM LAPACK F77 MIRLIB
# Use the generic AIPS++ test makefile.
#------------------------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.tst
