# $Id$
XLIBLIST:=Motif PGPLOT WCSLIB XPM X11 F77
# Use the generic AIPS++ test makefile.
#------------------------------------------------------
include $(word 1, $(CASAPATH))/code/install/makefile.tst
