CasaTaskDict = {
                   'hif_antpos'     : 'Antpos',
                   'hif_applycal'   : 'Applycal',
                   'hif_bandpass'   : 'Bandpass',
		   'hif_cleanlist'  : 'CleanList', 
                   'hif_exportdata' : 'ExportData',
                   'hif_flagdata'   : 'FlagDeterALMA',
                   'hif_gaincal'    : 'Gaincal',
                   'hif_newgaincal' : 'NewGaincal',
                   'hif_gfluxscale' : 'GcorFluxscale',
                   'hif_importdata' : 'ImportData',
		   'hif_makecleanlist': 'MakeCleanList', 
                   'hif_refant'     : 'RefAnt',
                   'hif_setjy'      : 'Setjy',
                   'hif_tsyscal'    : 'Tsyscal',
                   'hif_tsysflag'   : 'Tsysflag',
                   'hif_tsysflagedges': 'Tsysflagedges',
                   'hif_wvrgcal'    : 'Wvrgcal',
                   'hif_wvrgcalflag': 'Wvrgcalflag',
                   'hsd_calsky'     : 'SDCalSky',
                   'hsd_caltsys'    : 'SDCalTsys',
                   'hsd_applycal'   : 'SDApplyCal',
                   'hsd_exportdata' : 'SDExportData',
                   'hsd_importdata' : 'SDImportData',
                   'hsd_inspectdata': 'SDInspectData',
                   'hsd_imaging'    : 'SDImaging',
                   'hsd_reduce'     : 'SDReduction'
               }
